### ISSUE TITLE
Liveness and readiness probe commands are incorrect for deploying locally

### ISSUE THREAD

**Issue by varunbpatil** [travisjeffery/proglog#7]
After following the instructions in the "Advertise Raft on the Fully Qualified Domain Name" section, the address argument to `grpc_health_probe` needs to specify the fqdn as well.

```yaml
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |-
              /bin/grpc_health_probe -addr=$HOSTNAME.proglog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.rpcPort}}
          initialDelaySeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |-
              /bin/grpc_health_probe -addr=$HOSTNAME.proglog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.rpcPort}}
          initialDelaySeconds: 10
```
